version: "3.9"

services:
  db:
    image: postgres:16
    container_name: flowcare_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: flowcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: flowcare_api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: